version: "3"

services:
  python-api:
    build: ./python-api
  mongo-db:
    build: ./mongo
    ports:
      - "27017:27017"
  server-go:
    build: ./server-go
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY==value
      - PRODUCTION=false
  sveltekit:
    build: ./sveltekit
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY==value
    