version: "3"

services:
  mongo-db:
    build: ./mongo
    ports:
      - "27017:27017"
    networks:
      - openchat-network

  server-go:
    build: ./server-go
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=value
      - PRODUCTION=false
      - MONGO_CONNECTION_STRING=mongodb://mongo-db:27017/openchat
      - MONGO_DB_NAME=openchat
      - AI_URL=http://localhost:8000/runsync
      - AI_AUTH_KEY=secret

    networks:
      - openchat-network

  sveltekit:
    build: ./sveltekit
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=value
      - HOST_PORT=3000
      - BACKEND_URL=http://server-go:8080
      - ORIGIN=http://localhost:3000
    networks:
      - openchat-network

networks:
  openchat-network:
