version: "3"

services:
# For local development we need to run python-api without docker
#  python-api:
#    build: ./python-api
  mongo-db:
    build: ./mongo
    ports:
      - "27017:27017"
    networks:
      - openchat-network

  server-go:
    build: ./server-go
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=value
      - PRODUCTION=false
    networks:
      - openchat-network

  sveltekit:
    build: ./sveltekit
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=value
      - BACKEND_URL=http://server-go:8080
    networks:
      - openchat-network

networks:
  openchat-network:
