# Use the official MongoDB image as the base image
FROM mongo


ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=toor
ENV MONGO_INITDB_DATABASE=openchat

# Copy a script to initialize the database and collection
# COPY init-mongo.js /docker-entrypoint-initdb.d/
